# Generated by Django 2.0.4 on 2018-07-01 21:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180702_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='detais',
            new_name='details',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
