# Generated by Django 2.0.7 on 2018-09-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sliderimage', models.FileField(blank=True, upload_to='')),
                ('tital', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('linktital', models.CharField(max_length=200)),
                ('linkurl', models.URLField()),
            ],
        ),
    ]
