# Generated by Django 2.0.7 on 2018-09-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featuretitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
            ],
        ),
        migrations.RenameModel(
            old_name='Features',
            new_name='Featurelist',
        ),
    ]
