# Generated by Django 2.0.7 on 2018-09-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewstitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('deciption', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Reviewlist',
        ),
    ]
