# Generated by Django 2.0.7 on 2018-09-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('date', models.DateField()),
            ],
        ),
    ]
