# Generated by Django 2.0.7 on 2018-09-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy', models.CharField(max_length=40)),
                ('job_hours', models.CharField(max_length=200)),
                ('job_locaton', models.CharField(max_length=300)),
                ('job_title', models.CharField(max_length=600)),
                ('job_description', models.TextField()),
                ('responsibility', models.TextField()),
                ('qualifications', models.TextField()),
                ('education', models.CharField(max_length=500)),
                ('salary', models.CharField(max_length=200)),
                ('other_benefits', models.CharField(max_length=400)),
                ('last_date', models.DateField()),
            ],
        ),
    ]
