# Generated by Django 2.0.7 on 2018-09-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_create_menu_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamTital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('deciption', models.TextField()),
            ],
        ),
    ]
