# Generated by Django 2.0.7 on 2018-09-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email',
            new_name='Email_stor',
        ),
    ]
