# Generated by Django 2.0.7 on 2018-09-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_auto_20180910_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_stor',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
