# Generated by Django 2.0.7 on 2018-09-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_auto_20180910_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_menu',
            old_name='Example',
            new_name='exammple',
        ),
    ]
