# Generated by Django 2.0.7 on 2018-09-10 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_auto_20180910_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_menu',
            old_name='exammple',
            new_name='Example',
        ),
    ]
