# Generated by Django 2.0.7 on 2018-09-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_auto_20180910_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('telephonnumber', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
