# Generated by Django 2.0.7 on 2018-09-17 13:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirments',
            name='description',
            field=ckeditor.fields.RichTextField(default=2),
            preserve_default=False,
        ),
    ]
