# Generated by Django 2.0.7 on 2018-09-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_requirments_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirments',
            name='education',
        ),
        migrations.RemoveField(
            model_name='requirments',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='requirments',
            name='job_hours',
        ),
        migrations.RemoveField(
            model_name='requirments',
            name='job_locaton',
        ),
        migrations.RemoveField(
            model_name='requirments',
            name='last_date',
        ),
        migrations.RemoveField(
            model_name='requirments',
            name='other_benefits',
        ),
        migrations.RemoveField(
            model_name='requirments',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='requirments',
            name='responsibility',
        ),
        migrations.RemoveField(
            model_name='requirments',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='requirments',
            name='vacancy',
        ),
        migrations.AlterField(
            model_name='requirments',
            name='job_title',
            field=models.CharField(max_length=400),
        ),
    ]
