# Generated by Django 2.0.7 on 2018-09-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_auto_20180917_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='sliderimage',
            field=models.FileField(upload_to=''),
        ),
    ]
